// ⚠️ 자동 생성 파일. 수정하지 마세요.
// 생성 스크립트: scripts/generate-tailwind-from-tokens.js
module.exports = {
  colors: {
    gray: {
      100: "var(--core-colors-gray-100)",
      200: "var(--core-colors-gray-200)",
      300: "var(--core-colors-gray-300)",
      400: "var(--core-colors-gray-400)",
      500: "var(--core-colors-gray-500)",
      600: "var(--core-colors-gray-600)",
      700: "var(--core-colors-gray-700)",
      800: "var(--core-colors-gray-800)",
      900: "var(--core-colors-gray-900)",
    },
    indigo: {
      100: "var(--core-colors-indigo-100)",
      200: "var(--core-colors-indigo-200)",
      300: "var(--core-colors-indigo-300)",
      400: "var(--core-colors-indigo-400)",
      500: "var(--core-colors-indigo-500)",
      600: "var(--core-colors-indigo-600)",
      700: "var(--core-colors-indigo-700)",
      800: "var(--core-colors-indigo-800)",
      900: "var(--core-colors-indigo-900)",
    },
    blue: {
      100: "var(--core-colors-blue-100)",
      200: "var(--core-colors-blue-200)",
      300: "var(--core-colors-blue-300)",
      400: "var(--core-colors-blue-400)",
      500: "var(--core-colors-blue-500)",
      600: "var(--core-colors-blue-600)",
      700: "var(--core-colors-blue-700)",
      800: "var(--core-colors-blue-800)",
      900: "var(--core-colors-blue-900)",
    },
    green: {
      100: "var(--core-colors-green-100)",
      200: "var(--core-colors-green-200)",
      300: "var(--core-colors-green-300)",
      400: "var(--core-colors-green-400)",
      500: "var(--core-colors-green-500)",
      600: "var(--core-colors-green-600)",
      700: "var(--core-colors-green-700)",
      800: "var(--core-colors-green-800)",
      900: "var(--core-colors-green-900)",
    },
    red: {
      100: "var(--core-colors-red-100)",
      200: "var(--core-colors-red-200)",
      300: "var(--core-colors-red-300)",
      400: "var(--core-colors-red-400)",
      500: "var(--core-colors-red-500)",
      600: "var(--core-colors-red-600)",
      700: "var(--core-colors-red-700)",
      800: "var(--core-colors-red-800)",
      900: "var(--core-colors-red-900)",
    },
    orange: {
      100: "var(--core-colors-orange-100)",
      200: "var(--core-colors-orange-200)",
      300: "var(--core-colors-orange-300)",
      400: "var(--core-colors-orange-400)",
      500: "var(--core-colors-orange-500)",
      600: "var(--core-colors-orange-600)",
      700: "var(--core-colors-orange-700)",
      800: "var(--core-colors-orange-800)",
      900: "var(--core-colors-orange-900)",
    },
    yellow: {
      100: "var(--core-colors-yellow-100)",
      200: "var(--core-colors-yellow-200)",
      300: "var(--core-colors-yellow-300)",
      400: "var(--core-colors-yellow-400)",
      500: "var(--core-colors-yellow-500)",
      600: "var(--core-colors-yellow-600)",
      700: "var(--core-colors-yellow-700)",
      800: "var(--core-colors-yellow-800)",
      900: "var(--core-colors-yellow-900)",
    },
    teal: {
      120: "var(--core-colors-teal-100)",
      200: "var(--core-colors-teal-200)",
      300: "var(--core-colors-teal-300)",
      400: "var(--core-colors-teal-400)",
      500: "var(--core-colors-teal-500)",
      600: "var(--core-colors-teal-600)",
      700: "var(--core-colors-teal-700)",
      800: "var(--core-colors-teal-800)",
      900: "var(--core-colors-teal-900)",
    },
    pink: {
      100: "var(--core-colors-pink-100)",
      200: "var(--core-colors-pink-200)",
      300: "var(--core-colors-pink-300)",
      400: "var(--core-colors-pink-400)",
      500: "var(--core-colors-pink-500)",
      600: "var(--core-colors-pink-600)",
      700: "var(--core-colors-pink-700)",
      800: "var(--core-colors-pink-800)",
      900: "var(--core-colors-pink-900)",
    },
    purple: {
      100: "var(--core-colors-purple-100)",
      200: "var(--core-colors-purple-200)",
      300: "var(--core-colors-purple-300)",
      400: "var(--core-colors-purple-400)",
      500: "var(--core-colors-purple-500)",
      600: "var(--core-colors-purple-600)",
      700: "var(--core-colors-purple-700)",
      800: "var(--core-colors-purple-800)",
      900: "var(--core-colors-purple-900)",
    },
    accent: {},
    bg: {},
    fg: {},
  },
  spacing: {
    xs: "var(--core-spacing-xs)",
    sm: "var(--core-spacing-sm)",
    lg: "var(--core-spacing-lg)",
    xl: "var(--core-spacing-xl)",
  },
  borderRadius: {
    sm: "var(--core-borderradius-sm)",
    lg: "var(--core-borderradius-lg)",
    xl: "var(--core-borderradius-xl)",
    card: "var(--theme-card-borderradius)",
  },
  fontFamily: {},
  fontSize: {
    xs: [
      "var(--core-fontsizes-xs)",
      {
        lineHeight: "var(--core-lineheights-body)",
      },
    ],
    sm: [
      "var(--core-fontsizes-sm)",
      {
        lineHeight: "var(--core-lineheights-body)",
      },
    ],
    body: [
      "var(--core-fontsizes-body)",
      {
        lineHeight: "var(--core-lineheights-body)",
      },
    ],
    h1: [
      "var(--core-fontsizes-h1)",
      {
        lineHeight: "var(--core-lineheights-heading)",
      },
    ],
    h2: [
      "var(--core-fontsizes-h2)",
      {
        lineHeight: "var(--core-lineheights-heading)",
      },
    ],
    h3: [
      "var(--core-fontsizes-h3)",
      {
        lineHeight: "var(--core-lineheights-heading)",
      },
    ],
    h4: [
      "var(--core-fontsizes-h4)",
      {
        lineHeight: "var(--core-lineheights-heading)",
      },
    ],
    h5: [
      "var(--core-fontsizes-h5)",
      {
        lineHeight: "var(--core-lineheights-heading)",
      },
    ],
    h6: [
      "var(--core-fontsizes-h6)",
      {
        lineHeight: "var(--core-lineheights-heading)",
      },
    ],
  },
  lineHeight: {},
  letterSpacing: {},
  opacity: {},
  boxShadow: {},
  borderWidth: {},
};
