export const HEADER_LINK = [
  { name: "로그인", href: "/login" },
  { name: "회원가입", href: "/sign-up" },
  { name: "이메일 로그인", href: "/email-login" },
  { name: "비밀번호 찾기", href: "/find-pw" },
  { name: "서비스 소개", href: "/hello" },
  { name: "매뉴얼", href: "/manual" },
  { name: "마이페이지", href: "/mypage" },
  { name: "타인 유저 프로필", href: "/user/1" },
  { name: "알림", href: "/alert" },
  { name: "채팅", href: "/chat" },
  { name: "공지사항", href: "/notice?tab=notice" },
  { name: "일반 분실 글쓰기", href: "/write/post?type=lost" },
  { name: "일반 습득 글쓰기", href: "/write/post?type=find" },
  { name: "일반 게시글 리스트", href: "/list" },
  { name: "일반 게시글 상세", href: "/list/1" },
];
