export const CHANGE_EMAIL_INPUT_CONFIG = [
  {
    name: "email",
    label: "아이디(이메일)",
    type: "text",
    placeholder: "로그인에 사용할 이메일을 입력해주세요.",
    children: "인증번호 발송",
    maxLength: 256,
  },
  {
    name: "emailAuth",
    label: "이메일 인증",
    type: "text",
    placeholder: "인증번호를 입력해주세요.",
    children: "인증번호 확인",
    successMessage: "인증되었습니다.",
    maxLength: 6,
  },
  {
    name: "password",
    label: "비밀번호",
    type: "password",
    placeholder: "비밀번호을 입력해 주세요.",
    rule: "8~16자리, 대문자/소문자/숫자/특수 문자 포함",
    eyeShow: true,
    successMessage: "대문자/소문자/숫자/특수 문자 포함 8~16자리 사이",
    maxLength: 16,
  },
  {
    name: "passwordConfirm",
    label: "비밀번호 확인",
    type: "password",
    placeholder: "비밀번호 입력해 주세요.",
    eyeShow: true,
    successMessage: "비밀번호가 일치합니다.",
    maxLength: 16,
  },
];
