name: Chromatic (trusted authors auto)

on:
  pull_request_target:
    branches: [develop]

permissions:
  contents: read
  statuses: write

jobs:
  chromatic:
    # 내부 기여자만 허용 (OWNER, MEMBER, COLLABORATOR)
    if: contains(fromJson('["OWNER","MEMBER","COLLABORATOR"]'), github.actor_association)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR HEAD (trusted)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
